version: '3'
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../project:/app/project:ro
      - ../source:/app/source:ro
    ports:
      - ${WEB_PORT}
    depends_on:
      - php

  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}

  php:
    build:
      context: ../
      dockerfile: /dev/Dockerfile
    volumes:
      - ./project:/app
      - ../project:/app/project:ro
      - ../source:/app/source:ro
    depends_on:
      - postgres

volumes:
  postgres-data: